const IsiZuluData = {
    vowels: ['a', 'e', 'i', 'o', 'u'],
    consonants: ['b', 'bh', 'c', 'd', 'f', 'g', 'h', 'hl', 'j', 'k', 'l', 'm', 'n', 'ng', 'ny', 'p', 'ph', 'q', 'qh', 'r', 's', 'sh', 't', 'th', 'v', 'w', 'x', 'y', 'z'],

    letters: {
        a: { name: 'a', sound: 'ah', example: 'i-a', exampleWord: 'i-african', meaning: 'African', type: 'vowel' },
        b: { name: 'b', sound: 'buh', example: 'i-bhontshisi', exampleWord: 'ibhontshisi', meaning: 'bean', type: 'consonant' },
        bh: { name: 'bh', sound: 'bh', example: 'i-bhelikhosi', exampleWord: 'ibhelikhosi', meaning: 'balcony', type: 'consonant' },
        c: { name: 'c', sound: 'tsh', example: 'i-cula', exampleWord: 'icula', meaning: 'to sing', type: 'consonant' },
        d: { name: 'd', sound: 'd', example: 'i-danga', exampleWord: 'idanga', meaning: 'shield', type: 'consonant' },
        e: { name: 'e', sound: 'eh', example: 'i-ephendula', exampleWord: 'iphendula', meaning: 'to answer', type: 'vowel' },
        f: { name: 'f', sound: 'f', example: 'i-feni', exampleWord: 'ifeni', meaning: 'fan', type: 'consonant' },
        g: { name: 'g', sound: 'g', example: 'i-gilidi', exampleWord: 'igilidi', meaning: 'gate', type: 'consonant' },
        h: { name: 'h', sound: 'h', example: 'i-house', exampleWord: 'i-house', meaning: 'house', type: 'consonant' },
        hl: { name: 'hl', sound: 'hl', example: 'i-hle', exampleWord: 'ihle', meaning: 'beautiful', type: 'consonant' },
        i: { name: 'i', sound: 'ee', example: 'i-inkomo', exampleWord: 'inkomo', meaning: 'cow', type: 'vowel' },
        j: { name: 'j', sound: 'j', example: 'i-jam', exampleWord: 'ijamu', meaning: 'jam', type: 'consonant' },
        k: { name: 'k', sound: 'k', example: 'i-khathi', exampleWord: 'ikhathi', meaning: 'time', type: 'consonant' },
        l: { name: 'l', sound: 'l', example: 'i-loko', exampleWord: 'iloko', meaning: 'lock', type: 'consonant' },
        m: { name: 'm', sound: 'm', example: 'i-mama', exampleWord: 'mama', meaning: 'mother', type: 'consonant' },
        n: { name: 'n', sound: 'n', example: 'i-nja', exampleWord: 'inja', meaning: 'dog', type: 'consonant' },
        ng: { name: 'ng', sound: 'ng', example: 'i-ngane', exampleWord: 'ingane', meaning: 'child', type: 'consonant' },
        ny: { name: 'ny', sound: 'ny', example: 'i-nyoka', exampleWord: 'inyoka', meaning: 'snake', type: 'consonant' },
        o: { name: 'o', sound: 'oh', example: 'i-okuqala', exampleWord: 'okuqala', meaning: 'first', type: 'vowel' },
        p: { name: 'p', sound: 'p', example: 'i-paki', exampleWord: 'ipaki', meaning: 'park', type: 'consonant' },
        ph: { name: 'ph', sound: 'ph', example: 'i-phaphazi', exampleWord: 'iphaphazi', meaning: 'lung', type: 'consonant' },
        q: { name: 'q', sound: 'q', example: 'i-qhawe', exampleWord: 'iqhawe', meaning: 'hero', type: 'consonant' },
        qh: { name: 'qh', sound: 'qh', example: 'i-qhakaza', exampleWord: 'iqhakaza', meaning: 'to bloom', type: 'consonant' },
        r: { name: 'r', sound: 'r', example: 'i-radiyo', exampleWord: 'iradiyo', meaning: 'radio', type: 'consonant' },
        s: { name: 's', sound: 's', example: 'i-sikweleti', exampleWord: 'isikweleti', meaning: 'debt', type: 'consonant' },
        sh: { name: 'sh', sound: 'sh', example: 'i-shumi', exampleWord: 'ishumi', meaning: 'ten', type: 'consonant' },
        t: { name: 't', sound: 't', example: 'i-tabha', exampleWord: 'itabha', meaning: 'tub', type: 'consonant' },
        th: { name: 'th', sound: 'th', example: 'i-thango', exampleWord: 'ithango', meaning: 'fence', type: 'consonant' },
        u: { name: 'u', sound: 'oo', example: 'i-ulaka', exampleWord: 'iulaka', meaning: 'ulaka', type: 'vowel' },
        v: { name: 'v', sound: 'v', example: 'i-viili', exampleWord: 'iviili', meaning: 'wheel', type: 'consonant' },
        w: { name: 'w', sound: 'w', example: 'i-washi', exampleWord: 'iwashi', meaning: 'watch', type: 'consonant' },
        x: { name: 'x', sound: 'x', example: 'i-xakeka', exampleWord: 'ixakeka', meaning: 'busy', type: 'consonant' },
        y: { name: 'y', sound: 'y', example: 'i-yile', exampleWord: 'iyile', meaning: 'it is cold', type: 'consonant' },
        z: { name: 'z', sound: 'z', example: 'i-zulu', exampleWord: 'izulu', meaning: 'sky/weather', type: 'consonant' }
    },

    syllables: {
        'CV (Consonant-Vowel)': [
            { syllable: 'ba', sound: 'bah' },
            { syllable: 'be', sound: 'beh' },
            { syllable: 'bi', sound: 'bee' },
            { syllable: 'bo', sound: 'boh' },
            { syllable: 'bu', sound: 'boo' },
            { syllable: 'ka', sound: 'kah' },
            { syllable: 'ke', sound: 'keh' },
            { syllable: 'ki', sound: 'kee' },
            { syllable: 'ko', sound: 'koh' },
            { syllable: 'ku', sound: 'koo' },
            { syllable: 'la', sound: 'lah' },
            { syllable: 'le', sound: 'leh' },
            { syllable: 'li', sound: 'lee' },
            { syllable: 'lo', sound: 'loh' },
            { syllable: 'lu', sound: 'loo' },
            { syllable: 'ma', sound: 'mah' },
            { syllable: 'me', sound: 'meh' },
            { syllable: 'mi', sound: 'mee' },
            { syllable: 'mo', sound: 'moh' },
            { syllable: 'mu', sound: 'moo' },
            { syllable: 'na', sound: 'nah' },
            { syllable: 'ne', sound: 'neh' },
            { syllable: 'ni', sound: 'nee' },
            { syllable: 'no', sound: 'noh' },
            { syllable: 'nu', sound: 'noo' },
            { syllable: 'nga', sound: 'ngah' },
            { syllable: 'nge', sound: 'ngeh' },
            { syllable: 'ngi', sound: 'ngee' },
            { syllable: 'ngo', sound: 'ngoh' },
            { syllable: 'ngu', sound: 'ngoo' },
            { syllable: 'pa', sound: 'pah' },
            { syllable: 'pe', sound: 'peh' },
            { syllable: 'pi', sound: 'pee' },
            { syllable: 'po', sound: 'poh' },
            { syllable: 'pu', sound: 'poo' },
            { syllable: 'sa', sound: 'sah' },
            { syllable: 'se', sound: 'seh' },
            { syllable: 'si', sound: 'see' },
            { syllable: 'so', sound: 'soh' },
            { syllable: 'su', sound: 'soo' },
            { syllable: 'ta', sound: 'tah' },
            { syllable: 'te', sound: 'teh' },
            { syllable: 'ti', sound: 'tee' },
            { syllable: 'to', sound: 'toh' },
            { syllable: 'tu', sound: 'too' },
            { syllable: 'va', sound: 'vah' },
            { syllable: 've', sound: 'veh' },
            { syllable: 'vi', sound: 'vee' },
            { syllable: 'vo', sound: 'voh' },
            { syllable: 'vu', sound: 'voo' },
            { syllable: 'za', sound: 'zah' },
            { syllable: 'ze', sound: 'zeh' },
            { syllable: 'zi', sound: 'zee' },
            { syllable: 'zo', sound: 'zoh' },
            { syllable: 'zu', sound: 'zoo' }
        ],
        'CVC (Consonant-Vowel-Consonant)': [
            { syllable: 'ban', sound: 'bahn' },
            { syllable: 'ben', sound: 'behn' },
            { syllable: 'bin', sound: 'behn' },
            { syllable: 'bon', sound: 'bohn' },
            { syllable: 'bun', sound: 'boon' },
            { syllable: 'kal', sound: 'kahl' },
            { syllable: 'kel', sound: 'kehl' },
            { syllable: 'kil', sound: 'keel' },
            { syllable: 'kol', sound: 'kohl' },
            { syllable: 'kul', sound: 'kool' },
            { syllable: 'lam', sound: 'lahm' },
            { syllable: 'lem', sound: 'lehem' },
            { syllable: 'lim', sound: 'leem' },
            { syllable: 'lom', sound: 'lohm' },
            { syllable: 'lum', sound: 'loom' },
            { syllable: 'man', sound: 'mahn' },
            { syllable: 'men', sound: 'mehn' },
            { syllable: 'min', sound: 'meen' },
            { syllable: 'mon', sound: 'mohn' },
            { syllable: 'mun', sound: 'moon' },
            { syllable: 'nas', sound: 'nahs' },
            { syllable: 'nes', sound: 'nehs' },
            { syllable: 'nis', sound: 'nees' },
            { syllable: 'nos', sound: 'nohs' },
            { syllable: 'nus', sound: 'noos' },
            { syllable: 'ngam', sound: 'ngahm' },
            { syllable: 'ngem', sound: 'ngehm' },
            { syllable: 'ngim', sound: 'ngeem' },
            { syllable: 'ngom', sound: 'ngohm' },
            { syllable: 'ngum', sound: 'ngoom' },
            { syllable: 'pas', sound: 'pahs' },
            { syllable: 'pes', sound: 'pehs' },
            { syllable: 'pis', sound: 'pees' },
            { syllable: 'pos', sound: 'pohs' },
            { syllable: 'pus', sound: 'poos' },
            { syllable: 'sal', sound: 'sahl' },
            { syllable: 'sel', sound: 'sehl' },
            { syllable: 'sil', sound: 'seel' },
            { syllable: 'sol', sound: 'sohl' },
            { syllable: 'sul', sound: 'sool' },
            { syllable: 'tan', sound: 'tahn' },
            { syllable: 'ten', sound: 'tehn' },
            { syllable: 'tin', sound: 'teen' },
            { syllable: 'ton', sound: 'tohn' },
            { syllable: 'tun', sound: 'toon' },
            { syllable: 'val', sound: 'vahl' },
            { syllable: 'vel', sound: 'vehl' },
            { syllable: 'vil', sound: 'veel' },
            { syllable: 'vol', sound: 'vohl' },
            { syllable: 'vul', sound: 'vool' }
        ],
        'CCV (Consonant Cluster-Vowel)': [
            { syllable: 'bla', sound: 'blah' },
            { syllable: 'ble', sound: 'bleh' },
            { syllable: 'bli', sound: 'blee' },
            { syllable: 'bra', sound: 'brah' },
            { syllable: 'bre', sound: 'breh' },
            { syllable: 'dla', sound: 'dlah' },
            { syllable: 'dle', sound: 'dleh' },
            { syllable: 'dra', sound: 'drah' },
            { syllable: 'dre', sound: 'dreh' },
            { syllable: 'gla', sound: 'glah' },
            { syllable: 'gle', sound: 'gleh' },
            { syllable: 'gra', sound: 'grah' },
            { syllable: 'gre', sound: 'greh' },
            { syllable: 'kla', sound: 'klah' },
            { syllable: 'kle', sound: 'kleh' },
            { syllable: 'kra', sound: 'krah' },
            { syllable: 'kre', sound: 'kreh' },
            { syllable: 'pla', sound: 'plah' },
            { syllable: 'ple', sound: 'pleh' },
            { syllable: 'pra', sound: 'prah' },
            { syllable: 'pre', sound: 'preh' },
            { syllable: 'sla', sound: 'slah' },
            { syllable: 'sle', sound: 'sleh' },
            { syllable: 'sma', sound: 'smah' },
            { syllable: 'sme', sound: 'smeh' },
            { syllable: 'spa', sound: 'spah' },
            { syllable: 'spe', sound: 'speh' },
            { syllable: 'sta', sound: 'stah' },
            { syllable: 'ste', sound: 'steh' },
            { syllable: 'stra', sound: 'strah' },
            { syllable: 'stre', sound: 'streh' },
            { syllable: 'swa', sound: 'swah' },
            { syllable: 'swe', sound: 'sweh' },
            { syllable: 'tha', sound: 'thah' },
            { syllable: 'the', sound: 'theh' },
            { syllable: 'thi', sound: 'thee' },
            { syllable: 'tho', sound: 'thoh' },
            { syllable: 'thu', sound: 'thoo' },
            { syllable: 'twa', sound: 'twah' },
            { syllable: 'twe', sound: 'tweh' },
            { syllable: 'zwa', sound: 'zwah' },
            { syllable: 'zwe', sound: 'zweh' }
        ]
    },

    words: {
        'izilwane (Animals)': [
            { word: 'inja', meaning: 'dog', english: 'dog' },
            { word: 'ikati', meaning: 'cat', english: 'cat' },
            { word: 'inkomo', meaning: 'cow', english: 'cow' },
            { word: 'ihhashi', meaning: 'horse', english: 'horse' },
            { word: 'igundu', meaning: 'frog', english: 'frog' },
            { word: 'inyoka', meaning: 'snake', english: 'snake' },
            { word: 'ibhere', meaning: 'bear', english: 'bear' },
            { word: 'ingwenya', meaning: 'crocodile', english: 'crocodile' },
            { word: 'umbungulu', meaning: 'bee', english: 'bee' },
            { word: 'ijuba', meaning: 'pigeon', english: 'pigeon' }
        ],
        'abantu (People)': [
            { word: 'umama', meaning: 'mother', english: 'mother' },
            { word: 'ubaba', meaning: 'father', english: 'father' },
            { word: 'ingane', meaning: 'child', english: 'child' },
            { word: 'udokotela', meaning: 'doctor', english: 'doctor' },
            { word: 'umfundisi', meaning: 'teacher', english: 'teacher' },
            { word: 'umsakazi', meaning: 'radio', english: 'radio' },
            { word: 'umuntu', meaning: 'person', english: 'person' },
            { word: 'unina', meaning: 'her mother', english: 'her mother' },
            { word: 'uyise', meaning: 'his father', english: 'his father' },
            { word: 'abazali', meaning: 'parents', english: 'parents' }
        ],
        'izinto (Objects)': [
            { word: 'ibhuku', meaning: 'book', english: 'book' },
            { word: 'isikolo', meaning: 'school', english: 'school' },
            { word: 'itshala', meaning: 'pen', english: 'pen' },
            { word: 'ideskhi', meaning: 'desk', english: 'desk' },
            { word: 'ichair', meaning: 'chair', english: 'chair' },
            { word: 'iwindow', meaning: 'window', english: 'window' },
            { word: 'idoor', meaning: 'door', english: 'door' },
            { word: 'itshini', meaning: 'tin', english: 'tin' },
            { word: 'igama', meaning: 'name', english: 'name' },
            { word: 'isikhashana', meaning: 'small thing', english: 'small thing' }
        ],
        'izitsha (Food)': [
            { word: 'amadumbe', meaning: 'yams', english: 'yams' },
            { word: 'imifino', meaning: 'vegetables', english: 'vegetables' },
            { word: 'amasi', meaning: 'fermented milk', english: 'fermented milk' },
            { word: 'inkukhu', meaning: 'chicken', english: 'chicken' },
            { word: 'ubhontshisi', meaning: 'bean', english: 'bean' },
            { word: 'ibhanana', meaning: 'banana', english: 'banana' },
            { word: 'isWEsi', meaning: 'orange', english: 'orange' },
            { word: 'umango', meaning: 'mango', english: 'mango' },
            { word: 'amakhowe', meaning: 'mushrooms', english: 'mushrooms' },
            { word: 'ingulube', meaning: 'pig', english: 'pig' }
        ],
        'izinkomo (Nature)': [
            { word: 'ilanga', meaning: 'sun', english: 'sun' },
            { word: 'inyanga', meaning: 'moon', english: 'moon' },
            { word: 'inkanyezi', meaning: 'star', english: 'star' },
            { word: 'izulu', meaning: 'sky', english: 'sky' },
            { word: 'imanzi', meaning: 'water', english: 'water' },
            { word: 'umlilo', meaning: 'fire', english: 'fire' },
            { word: 'umhlaba', meaning: 'earth', english: 'earth' },
            { word: 'intaba', meaning: 'mountain', english: 'mountain' },
            { word: 'umfula', meaning: 'river', english: 'river' },
            { word: 'igceke', meaning: 'field', english: 'field' }
        ],
        'izibalo (Colors)': [
            { word: 'bomvu', meaning: 'red', english: 'red' },
            { word: 'luhlaza', meaning: 'green', english: 'green' },
            { word: 'luhlaza okwesibhakabhaka', meaning: 'blue', english: 'blue' },
            { word: 'nyulu', meaning: 'yellow', english: 'yellow' },
            { word: 'mhlophe', meaning: 'white', english: 'white' },
            { word: 'mnyama', meaning: 'black', english: 'black' },
            { word: 'nsundu', meaning: 'brown', english: 'brown' },
            { word: 'ngoqo', meaning: 'orange', english: 'orange' },
            { word: 'violet', meaning: 'purple', english: 'purple' },
            { word: 'pinki', meaning: 'pink', english: 'pink' }
        ]
    },

    sentences: {
        'Isivakalisi Esisodwa (Simple Sentences)': [
            { sentence: 'Umama upheka.', meaning: 'Mother is cooking.', words: ['Umama', 'upheka'] },
            { sentence: 'Ubaba ehamba.', meaning: 'Father is going.', words: ['Ubaba', 'ehamba'] },
            { sentence: 'Ingane idlala.', meaning: 'The child is playing.', words: ['Ingane', 'idlala'] },
            { sentence: 'Inja igijima.', meaning: 'The dog is running.', words: ['Inja', 'igijima'] },
            { sentence: 'Ikati ihleli.', meaning: 'The cat is sitting.', words: ['Ikati', 'ihleli'] },
            { sentence: 'Isikolo sivulekile.', meaning: 'The school is open.', words: ['Isikolo', 'sivulekile'] },
            { sentence: 'Ilanga liphumile.', meaning: 'The sun has come out.', words: ['Ilanga', 'liphumile'] },
            { sentence: 'Manzi amanzi.', meaning: 'The water is water.', words: ['Manzi', 'amanzi'] }
        ],
        'Izivakalisi Ezimfishi (Short Sentences)': [
            { sentence: 'Ingane ifunda esikoleni.', meaning: 'The child learns at school.', words: ['Ingane', 'ifunda', 'esikoleni'] },
            { sentence: 'Umama upheka ukudla.', meaning: 'Mother is cooking food.', words: ['Umama', 'upheka', 'ukudla'] },
            { sentence: 'Ubaba ubuya emsebenzini.', meaning: 'Father is coming from work.', words: ['Ubaba', 'ubuya', 'emsebenzini'] },
            { sentence: 'Inja yakami ihleli phansi.', meaning: 'My dog is sitting down.', words: ['Inja', 'yakami', 'ihleli', 'phansi'] },
            { sentence: 'Isikolo siqalile.', meaning: 'The school has started.', words: ['Isikolo', 'siqalile'] },
            { sentence: 'Ilanga libusuku.', meaning: 'The sun is setting.', words: ['Ilanga', 'libusuku'] }
        ],
        'Izivakalisi Ezinde (Long Sentences)': [
            { sentence: 'Ingane ifunda kahle esikoleni sakibo.', meaning: 'The child learns well at their school.', words: ['Ingane', 'ifunda', 'kahle', 'esikoleni', 'sakibo'] },
            { sentence: 'Umama wake upheka ukudla okumnandi.', meaning: 'His mother cooks delicious food.', words: ['Umama', 'wake', 'upheka', 'ukudla', 'okumnandi'] },
            { sentence: 'Babedlala e gardenini ngeSonwabo.', meaning: 'They were playing in the garden with joy.', words: ['Babedlala', 'e', 'gardenini', 'ngeSonwabo'] },
            { sentence: 'Izinkomo zidla grass endlebeni.', meaning: 'The cows eat grass in the field.', words: ['Izinkomo', 'zidla', 'grass', 'endlebeni'] },
            { sentence: 'Abantwana bayajabula esikoleni.', meaning: 'The children are happy at school.', words: ['Abantwana', 'bayajabula', 'esikoleni'] }
        ]
    },

    stories: {
        'Indaba Yengane (The Child\'s Story)': {
            title: 'Ingane Nejahe',
            paragraphs: [
                { zulu: 'Kwakukhona ingane ebizwa ngokuthi uSipho.', english: 'There was a child named Sipho.' },
                { zulu: 'USipho wayezithanda izilwane kakhulu.', english: 'Sipho loved animals very much.' },
                { zulu: 'Ngephuzu, wathola ijahe elincane elilahlekile.', english: 'One day, he found a small lost chick.' },
                { zulu: 'Wagcina ijahe wayinakekela kahle.', english: 'He took care of the chick very well.' },
                { zulu: 'Ngemva kwesikhathi, ijahe lakula liba nkulu.', english: 'After some time, the chick grew big.' },
                { zulu: 'USipho wayejabula kakhulu ngenxa yalo.', english: 'Sipho was very happy because of it.' }
            ]
        },
        'Indaba Yenzuku (The Sun Story)': {
            title: 'Ilanga Nesondo',
            paragraphs: [
                { zulu: 'Ilanga laliphakeme esibhakabhakeni.', english: 'The sun was high in the sky.' },
                { zulu: 'Abantwana babedlala ngaphandle.', english: 'The children were playing outside.' },
                { zulu: 'Ngqo, amafu aqala ukuvela.', english: 'Suddenly, clouds started to appear.' },
                { zulu: 'Umvula waqala ukunyuka.', english: 'Rain started to fall.' },
                { zulu: 'Abantwana bangena endlini.', english: 'The children went inside the house.' },
                { zulu: 'Emva kwemvula, injula yafika.', english: 'After the rain, a rainbow appeared.' },
                { zulu: 'Bonke abantwana babehleli bebuka injula.', english: 'All the children sat watching the rainbow.' }
            ]
        },
        'Indaba Yempi (The Cow Story)': {
            title: 'Inkomo Emhlophe',
            paragraphs: [
                { zulu: 'Kwakukhona inkomo emhlophe endle.', english: 'There was a white cow in the field.' },
                { zulu: 'Inkomo yayidla grass yonke indawo.', english: 'The cow ate grass everywhere.' },
                { zulu: 'Ngosuku olunye, inkomo ayizange ibuyele endlini.', english: 'One day, the cow did not return home.' },
                { zulu: 'Umnikazi wayo wayozama ukuyifuna.', english: 'Its owner tried to look for it.' },
                { zulu: 'Wamthola esontweni, edla amagile.', english: 'He found it at the pond, eating reeds.' },
                { zulu: 'Wamngenisa endlini, wajabula kakhulu.', english: 'He brought it inside, very happy.' }
            ]
        },
        'Indaba Yemfundo (The Learning Story)': {
            title: 'Umfundi Omusha',
            paragraphs: [
                { zulu: 'Kwakukhona inkosazana ebizwa ngoNoma.', english: 'There was a princess named Noma.' },
                { zulu: 'UNoma wayefuna ukufunda ukufunda.', english: 'Noma wanted to learn to read.' },
                { zulu: 'Waqala ngokufunda izinhlaka.', english: 'She started by learning letters.' },
                { zulu: 'Ngemva kwalokho, wafunda izingxenye.', english: 'After that, she learned syllables.' },
                { zulu: 'Kancane kancane, wafunda amagama.', english: 'Gradually, she learned words.' },
                { zulu: 'Ekugcineni, yayifunda izindaba zonke.', english: 'Finally, she could read all stories.' },
                { zulu: 'UNoma wayejabula kakhulu ngemfundo yakhe.', english: 'Noma was very happy with her education.' }
            ]
        }
    },

    levelNames: {
        letters: { zulu: 'Izinhlaka', english: 'Letters' },
        syllables: { zulu: 'Izingxenye', english: 'Syllables' },
        words: { zulu: 'Amagama', english: 'Words' },
        sentences: { zulu: 'Izivakalisi', english: 'Sentences' },
        stories: { zulu: 'Izindaba', english: 'Stories' }
    }
};
